services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./src/test/resources/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./certs:/crt:ro
